import { asc, eq } from "drizzle-orm";
import { NextResponse } from "next/server";

import { db } from "@/db";
import { auditLogs, users } from "@/db/schema";
import { hashPassword, requireRole } from "@/lib/auth";

function errorResponse(error: unknown) { const message = error instanceof Error ? error.message : "UNKNOWN"; const status = message === "AUTH_REQUIRED" ? 401 : message === "FORBIDDEN" ? 403 : 400; return NextResponse.json({ error: message }, { status }); }

export async function GET() { try { await requireRole(["admin"]); const items = await db.select({ id: users.id, email: users.email, displayName: users.displayName, role: users.role, isActive: users.isActive, createdAt: users.createdAt, updatedAt: users.updatedAt }).from(users).orderBy(asc(users.email)); return NextResponse.json({ items }); } catch (error) { return errorResponse(error); } }

export async function POST(request: Request) { try { const actor = await requireRole(["admin"]); const body = await request.json(); const email = String(body.email ?? "").trim().toLowerCase(); const displayName = String(body.displayName ?? "").trim(); const password = String(body.password ?? ""); const role = body.role === "publisher" ? "publisher" : body.role === "editor" ? "editor" : "admin"; if (!email || !displayName || password.length < 12) return NextResponse.json({ error: "Email, display name, and a 12+ character password are required" }, { status: 400 }); const [item] = await db.insert(users).values({ email, displayName, passwordHash: hashPassword(password), role }).returning({ id: users.id, email: users.email, displayName: users.displayName, role: users.role, isActive: users.isActive, createdAt: users.createdAt, updatedAt: users.updatedAt }); await db.insert(auditLogs).values({ actorId: actor.id, action: "user.create", entityType: "user", entityId: item.id, metadata: { email: item.email, role: item.role } }); return NextResponse.json({ item }, { status: 201 }); } catch (error) { return errorResponse(error); } }

export async function PATCH(request: Request) { try { const actor = await requireRole(["admin"]); const body = await request.json(); if (!body.id) return NextResponse.json({ error: "User id is required" }, { status: 400 }); const role = body.role === "publisher" ? "publisher" : body.role === "editor" ? "editor" : "admin"; const [item] = await db.update(users).set({ role, isActive: body.isActive !== false, displayName: body.displayName ? String(body.displayName).trim() : undefined, updatedAt: new Date() }).where(eq(users.id, body.id)).returning({ id: users.id, email: users.email, displayName: users.displayName, role: users.role, isActive: users.isActive, createdAt: users.createdAt, updatedAt: users.updatedAt }); if (!item) return NextResponse.json({ error: "User not found" }, { status: 404 }); await db.insert(auditLogs).values({ actorId: actor.id, action: "user.update", entityType: "user", entityId: item.id, metadata: { email: item.email, role: item.role, isActive: item.isActive } }); return NextResponse.json({ item }); } catch (error) { return errorResponse(error); } }
